### ISSUE TITLE
We are finding that some civi registrants re not getting pushed to Moodle

### ISSUE THREAD

**Issue by petednz** [JMAConsulting/biz.jmaconsulting.civimoodle#14]
Hi - do you have any hints on what we can do in a situation where - for reasons we haven't yet figured - a person who registers for a sync'ed civi-moodle event does not end up with a moodle record?

I was hoping there was something I could try, like resaving the event rego, which might retrigger the sync, and in doing so, if it fails it might provide some hints as to why it is failing.

We also have SAML login from Drupal to moodle. and not suggesting this is causing the issue (since others are succeeding find), but it does mean that if while logged in to Drupal as them, we visit the SAML url for moodle, then a Moodle user is generated. which means we then have a moodle ID which I can enter in to the civi 'moodle id' field, but even that, and resaving the event rego, does not result in the moodle user being registered for the course in moodle.

Anything i can try with API Explorer? I don't see any 'jobs' i can rerun in scheduled jobs.

Thanks for any thoughts on this.

**Comment by petednz** [comment]
Found a couple of drupal errors

> Notice: Undefined variable: passwordKey in civimoodle_civicrm_buildForm() (line 129 of /srv/www/production/<site>/sites/default/civicrm/ext/biz.jmaconsulting.civimoodle/civimoodle.php).

and

> Deprecated function: Non-static method CRM_Civimoodle_Util::convertToUserName() should not be called statically in CRM_Civimoodle_Util::createUser() (line 71 of /srv/www/production/<site>/sites/default/civicrm/ext/biz.jmaconsulting.civimoodle/CRM/Civimoodle/Util.php).

**Comment by monishdeb** [comment]
Hi @petednz, thanks for the report about this issue and for mentioning the drupal errors. However, as per the second warning, there is no `CRM_Civimoodle_Util::convertToUserName()` function implemented the Util class [here](https://github.com/JMAConsulting/biz.jmaconsulting.civimoodle/blob/master/CRM/Civimoodle/Util.php) and didn't see the  `passwordKey` use in line 129. Is there any customization involved in the civimoodle extension?  

During the course enrollment process, the code checks if the registrant has Moodle user ID or moodle user credential. If not, that is for new Moodle user, it creates a new moodle user account and uses the user ID to enroll the registrant to respective Moodle courses. In this case, I think there might be some customization involved or internal failure from Moodle's end. The internal failures are recorded in the CiviCRM's system log [here](https://github.com/JMAConsulting/biz.jmaconsulting.civimoodle/blob/master/CRM/Civimoodle/API.php#L179). Can you please check the SystemLog entries via API explorer or DB? 

On the other hand, there is no API declared to enroll moodle users in respective courses separately or schedule job to sync the moodle course enrollment, but the utility function to process the course enrollment is defined at `CRM_Civimoodle_Util::enrollUser($courses, $moodleUserID)`.

Please let me know the internal errors you are encountering for those failed course enrolments.

**Comment by stesi561** [comment]
In this case there is some customisations involved - you can close this.
