### ISSUE TITLE
Uppercase usernames makes account creation and course enrollment fail

### ISSUE THREAD

**Issue by guapuruvu** [JMAConsulting/biz.jmaconsulting.civimoodle#3]
Hi Monish and Joe, a user successfully registered for a course using CiviEvents on [the CNS website](https://cooperativenewschool.com), but an account was not created in Moodle and they weren't enrolled in the corresponding course in[ the CNS's Moodle site](https://learn.cooperativenewschool.com).

I think this is because they chose capital letters in the username they passed to CiviMoodle, and [Moodle doesn't allow capital letters](https://moodle.org/mod/forum/discuss.php?d=143703). Is there a way to correct this behavior of CiviMoodle, or somehow configure limitations of valid entries in CiviCRM?

**Comment by guapuruvu** [comment]
I just enabled "Allow extended characters in usernames" in Moodle security settings, but I still can't seem to use uppercase characters in usernames.

**Comment by JoeMurray** [comment]
Monish, please investigate, and provide guidance on how to avoid this bug or fix. Ideally we could document setting @guapuruvu mentions if you can get that to work.

@guapuruvu could you provide a single quoted user name that caused the issue, eg 'Joe Murray' ? Thanks.

**Comment by guapuruvu** [comment]
'Jrburton'

**Comment by monishdeb** [comment]
@JoeMurray @guapuruvu, unfortunately, its an issue from moodle end which is not yet solved in the latest version. This is the current issue https://tracker.moodle.org/browse/MDL-9989 which is still open, though it has few patches to fix the problem in Moodle core but as per the comments it's a partial fix and need through testing. I investigated a bit more and found that enabling "Allow extended characters in usernames" in Moodle security settings didn't fix this issue, instead, on various forum like [here](https://peaceloveandmoodle.wordpress.com/2017/06/27/always-set-usernames-to-lowercase/), they suggested to enforce lowercase username before making moodle API request. Such fix can be done in this extension and would take another 30min for fix+QA.

**Comment by JoeMurray** [comment]
@guapuruvu please reopen if you like to fund this enhancement.
