### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by joemcl** [JMAConsulting/biz.jmaconsulting.civimoodle#4]
Just installed this on Civi 5.18.3 and Drupal 7.67. I found the basic config settings at Administer -> System Settings -> CiviCRM Moodle Integration and will try to set that up. But some more documentation would be handy. I've never used Moodle but have heard good things, going to check it out and attempt the integration.

**Comment by jamienovick** [comment]
@joemcl @JoeMurray Just wondering what the current status of this extension is? Is it in use? Could I ask which versions of CiviCRM are known to be supported? May want to dust this off for a client. Best :)

**Comment by joemcl** [comment]
@jamienovick I set it up on a demo site, but I haven't really used it. I'll dust it off tonight.

**Comment by joemcl** [comment]
See this re CLINIC, Moodle and CiviCRM - so at least as of Nov 2017 it was using CIviCRM and Moodle -  https://civicrm.org/jobs/e-learning-program-developer

**Comment by JoeMurray** [comment]
We actively maintain the extension. It is in use on two clients' sites running current versions of Civi.

**Comment by monishdeb** [comment]
I have added a documentation page in here https://github.com/JMAConsulting/biz.jmaconsulting.civimoodle/wiki/CiviMoodle
