### ISSUE TITLE
add links/refs to any existing CiviCRM training courses or other orgs that use the Moodle integration

### ISSUE THREAD

**Issue by joemcl** [JMAConsulting/biz.jmaconsulting.civimoodle#5]
If there are orgs or CiviCRM Partners that have created CiviCRM training courses using Moodle, that would be handy to know. Also, if there is a list of orgs using the CiviCRM Moodle integration for courses of any type, would also be very handy to know.

**Comment by JoeMurray** [comment]
The original development and some enhancements have been funded by https://www.bcadoption.com/education who still use it.

**Comment by joemcl** [comment]
cool thanks and it looks like https://cliniclegal.org might be using it as well.
