### ISSUE TITLE
Registrations not being sent to Moodle

### ISSUE THREAD

**Issue by KilakwaBT** [JMAConsulting/biz.jmaconsulting.civimoodle#8]
We are having an issue with registrations being sent to Moodle. We can see the courses in the event set up and assign them to the event. When we register a participant the are not registered for the course on the Moodle end. Here is our envoroment:

CiviCRM 5.28.2
WordPress 5.5.1
We use the Edwiser Bridge Plugin w/SSO extension to provide quick back and forth for users.

The courses are free but users must be signed in. A couple things I have noticed.
* There are no errors on front end registration. When I register in the back end I get a Moodle credentials not found unless I insert them in the custom fields mannually. I do have use CMS credentials for Moodle checked in the setup.

I feel like I am missing something in the setup that is preventing the registrations from being pushed to Moodle.

Thanks in advance for any insight.

**Comment by JoeMurray** [comment]
@monishdeb could you reply? Thx.

**Comment by JoeMurray** [comment]
@KilakwaBT : @monishdeb reminded me that this was a Drupal only implementation. Sorry for the lack of documentation on that. We'll try to address that lack shortly. We'd be happy to do a WP integration if you want or accept a PR for that.

**Comment by JoeMurray** [comment]
Created enhancement ticket for WordPress support https://github.com/JMAConsulting/biz.jmaconsulting.civimoodle/issues/10. Closing this as duplicate.
