### ISSUE TITLE
Server error on registering people for events

### ISSUE THREAD

**Issue by jrobens** [JMAConsulting/biz.jmaconsulting.civimoodle#9]
CiviCRM 5.33.2 with civmoodle installed. Under some circumstances registering a person for an event causes a server error message to be presented. 

Investigated and found 

`
Error: Call to undefined method CRM_Core_BAO_Cache::setItem() in civimoodle_civicrm_post() (line 221 of /srv/web/climatebonds.net/web/files/civicrm/ext/biz.jmaconsulting.civimoodle/civimoodle.php).
`

```
Error: Call to undefined method CRM_Core_BAO_Cache::deleteGroup() in          
                                             civimoodle_civicrm_post() (line 220 of
```

DeleteGroup also in line 109. 

Lint checker also finds an error at 

`$courses = CRM_Core_BAO_Cache::getItem("moodle courses", 'civimoodle_civicrm_post');`

**Comment by jrobens** [comment]
I have forked this code. What happens when cache retrieval fails on courses? https://github.com/jrobens/biz.jmaconsulting.civimoodle. Line 103.

**Comment by jrobens** [comment]
'CRM_Core_BAO_Cache::getItem. Added deprecation message  in CiviCRM core cf4c32ddeea91eee6f4a8fd30a92b288d9120a69

Says to use Civi::cache() facade or define cache group using hook_civicrm_container'

**Comment by JoeMurray** [comment]
@monishdeb could you review the report above.
